ui <- fluidPage(
    sidebarPanel(
        sliderInput(inputId = "power",
                    label   = "Power (1 - Beta)",
                    value   = 0.9,
                    min     = 0,
                    max     = 1,
                    step    = 0.01,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "sig.level",
                    label   = "Significance Level",
                    value   = 0.01,
                    min     = 0.00001,
                    max     = 0.1,
                    step    = 0.00001,
                    round   = FALSE,
                    ticks   = TRUE),
        selectInput(inputId  = "pkg",
                    label    = "Package",
                    selected = "pwr",
                    choices  = c("pwr" = "pwr",
                                 "samplesize"   = "samplesize",
                                 "TrialSize"    = "TrialSize",
                                 "clusterPower" = "clusterPower",
                                 "longpower"    = "longpower",
                                 "PowerTOST"    = "PowerTOST")),
        ## Conditional on the pkg chosen the options of which functions
        ## to use from that pkg are now displayed...
        conditionalPanel(
            condition = "input.pkg == 'pwr'",
            selectInput(inputId  = "test",
                        label    = "Function from pwr pkg",
                        selected = NULL,
                        choices  = c("One-sample Proportion"                = "pwr.p.test",
                                     "Two-sample Proportion (Equal Size)"   = "pwr.2p.test",
                                     "Two-sample Proportion (Unequal Size)" = "pwr.2p2n.test",
                                     "T-test (Equal Size)"                  = "pwr.t.test",
                                     "T-test (Unequal Size)"                = "pwr.t2n.test",
                                     "ANOVA (One-way Balanched)"            = "pwr.anova.test",
                                     "Correlation Test"                     = "pwr.r.test",
                                     "Chi-squared Test"                     = "pwr.chisq.test",
                                     "General Linear Model"                 = "pwr.f2.test"))
        ),
        conditionalPanel(
            condition = "input.pkg == 'samplesize'",
            selectInput(inputId  = "test",
                        label    = "Function from samplesize package",
                        selected = NULL,
                        choices  = c("T-Test of Means" = "n.ttest",
                                     "Wilcoxon-Mann-Whitney for Ordinal Data" = "n.wilcox.ord"))
        ),
        conditionalPanel(
            condition = "input.pkg == 'TrialSize'",
            selectInput(inputId  = "test",
                        label    = "Function from TrialSize package",
                        selected = NULL,
                        choices  = c("ANOVA - Pairwise Comparison for Multiple Sample One-Way" = "OneWayANOVA.pairwise",
                                     "ANOVA - One-Way Pairwise Comparison" = "OneWayANOVA/PariwsieComparison",
                                     "ANOVA - Repeated Measures" = "ANOVA.Repeat.Measure",
                                     "Average Bioequivalence" = "ABE",
                                     "Cox Proportional Hazard Test for Equality" = "Cox.Equality",
                                     "Cox Proportional Hazard Test for Equivalence" = "Cox.Eequivalence",
                                     "Cox Proportional Hazard Test for Non-Inferiority/Superiority" = "Cox.NIS",
                                     "One Sample Mean Test for Equality" = "OneSampleMean.Equality",
                                     "One Sample Mean Test for Equivalence" = "OneSampleMean.Equivalence",
                                     "One Sample Mean Test for Non-Inferiority/Superiority" = "OneSampleMean.NIS",
                                     "One Sample Proportion Test for Equality" = "OneSampleProportion.Equality",
                                     "One Sample Proportion Test for Equivalence" = "OneSampleProportion.Equivalence",
                                     "One Sample Proportion Test for Non-Inferiority/Superiority" = "OneSampleProportion.NIS"))
            ## ToDo - Add all possible models
                                     ## "" = "",
                                     ## "" = "",
                                     ## "" = "",
                                     ## "" = "",
                                     ## "" = ""))
        ),
        conditionalPanel(
            condition = "input.pkg == 'clusterPower'",
            selectInput(inputId  = "test",
                        label    = "Function from clusterPower package",
                        selected = NULL,
                        choices  = c("Continuous Outcome"    = "crtpwr.2mean",
                                     "Binary Outcome"        = "crtpwr.2prop",
                                     "Count (Rate) Outcome " = "crtpwr.2rate",
                                     "Coefficient of Variation" = "hayes.power.poisson"))
        ),
        conditionalPanel(
            condition = "input.pkg == 'longpower'",
            selectInput(inputId  = "test",
                        label    = "Function from longpower package",
                        selected = NULL,
                        choices  = c("Difference in slopes between two groups" = "diggle.linear.power",
                                     "Linear Mixed Model Sample Size Calculations" = "edland.linear.power",
                                     "Linear mixed model sample size calculations (Liu & Liang)" = "liu.liang.linear.power"))
            ## ToDo - Add all possible methods
                                     ## "Sample Size Calculations for Linear Mixed Models of Rate of Change based on pilot estimates " = "lmmpower",
                                     ## "" = ""))
        ),
        ## ToDo - Add functions from this package
        ## conditionalPanel(
        ##     condition = "input.pkg == 'PowerTOST'",
        ##     selectInput(inputId  = "test",
        ##                 label    = "Function from PowerTOST package",
        ##                 selected = NULL,
        ##                 choices  = c("" = "",
        ##                              "" = ""))
        ## )
        ## Now that the function has been chosen present the user with the options
        ## specific to that package
        conditionalPanel(
            condition = "input.test == 'pwr.p.test'",
            sliderInput(inputId = "p1",
                        label   = "Proportion 1",
                        value   = 0.5,
                        min     = 0,
                        max     = 1,
                        step    = 0.001,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "p2",
                        label   = "Proportion 2",
                        value   = 0.4,
                        min     = 0,
                        max     = 1,
                        step    = 0.001,
                        round   = FALSE,
                        ticks   = TRUE),
            selectInput(inputId  = "alternative",
                        label    = "Alternative Hypothesis",
                        selected = "two.sided",
                        choices  = c("Two-Sided" = "two.sided",
                                     "Greater"   = "greater",
                                     "Less"      = "less"))
        ),
        conditionalPanel(
            condition = "input.test == 'pwr.2p.test'",
            sliderInput(inputId = "p1",
                        label   = "Proportion 1",
                        value   = 0.5,
                        min     = 0,
                        max     = 1,
                        step    = 0.001,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "p2",
                        label   = "Proportion 2",
                        value   = 0.4,
                        min     = 0,
                        max     = 1,
                        step    = 0.001,
                        round   = FALSE,
                        ticks   = TRUE),
            selectInput(inputId  = "alternative",
                        label    = "Alternative Hypothesis",
                        selected = "two.sided",
                        choices  = c("Two-Sided" = "two.sided",
                                     "Greater"   = "greater",
                                     "Less"      = "less"))
        ),
        conditionalPanel(
            condition = "input.test == 'pwr.2p2n.test'",
            sliderInput(inputId = "p1",
                        label   = "Proportion 1",
                        value   = 0.5,
                        min     = 0,
                        max     = 1,
                        step    = 0.001,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "p2",
                        label   = "Proportion 2",
                        value   = 0.4,
                        min     = 0,
                        max     = 1,
                        step    = 0.001,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "n1",
                        label   = "Number of obs in second sample",
                        value   = 100,
                        min     = 0,
                        max     = 10000,
                        step    = 1,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "n2",
                        label   = "Number of obs in second sample",
                        value   = NULL,
                        min     = 0,
                        max     = 10000,
                        step    = 1,
                        round   = FALSE,
                        ticks   = TRUE),
            selectInput(inputId  = "alternative",
                        label    = "Alternative Hypothesis",
                        selected = "two.sided",
                        choices  = c("Two-Sided" = "two.sided",
                                     "Greater"   = "greater",
                                     "Less"      = "less"))
        ),
        conditionalPanel(
            condition = "input.test == 'pwr.t.test'",
            sliderInput(inputId = "d",
                        label   = "Effect Size (Cohen's D)",
                        value   = 0.2,
                        min     = 0,
                        max     = 2,
                        step    = 0.01,
                        round   = FALSE,
                        ticks   = TRUE),
            selectInput(inputId  = "type",
                        label    = "Type of T-Test",
                        selected = "one",
                        choices  = c("One Sample"  = "one.sample",
                                     "Two Sample"  = "two.sample",
                                     "Paired"      = "paired")),
            selectInput(inputId  = "alternative",
                        label    = "Alternative Hypothesis",
                        selected = "two.sided",
                        choices  = c("Two-Sided" = "two.sided",
                                     "Greater"   = "greater",
                                     "Less"      = "less"))
        ),
        conditionalPanel(
            condition = "input.test == 'pwr.t2n.test'",
            sliderInput(inputId = "d",
                        label   = "Effect Size (Cohen's D)",
                        value   = 0.2,
                        min     = 0,
                        max     = 2,
                        step    = 0.01,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "n1",
                        label   = "Number of obs in second sample",
                        value   = 100,
                        min     = 0,
                        max     = 10000,
                        step    = 1,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "n2",
                        label   = "Number of obs in second sample",
                        value   = NULL,
                        min     = 0,
                        max     = 10000,
                        step    = 1,
                        round   = FALSE,
                        ticks   = TRUE),
            selectInput(inputId  = "alternative",
                        label    = "Alternative Hypothesis",
                        selected = "two.sided",
                        choices  = c("Two-Sided" = "two.sided",
                                     "Greater"   = "greater",
                                     "Less"      = "less"))
        ),
        conditionalPanel(
            condition = "input.test == 'pwr.anova.test'",
            sliderInput(inputId = "f",
                        label   = "Effect Size (f)",
                        value   = 0.2,
                        min     = 0,
                        max     = 2,
                        step    = 0.01,
                        round   = FALSE,
                        ticks   = TRUE),
            sliderInput(inputId = "k",
                        label   = "Number of groups",
                        value   = 2,
                        min     = 0,
                        max     = 10,
                        step    = 1,
                        round   = FALSE,
                        ticks   = TRUE),
        ) ## ,
        ## conditionalPanel(
        ##     condition = "input.test == 'pwr.r.test'",
        ## ),
        ## conditionalPanel(
        ##     condition = "input.test == 'pwr.chisq.test'",
        ## ),
        ## conditionalPanel(
        ##     condition = "input.test == 'pwr.f.test'",
        ## )
    )
    mainPanel(

    )
)
