        menuItem("About",        tabName = "about",        icon = icon("dashboard")),
        menuItem("pwr",          tabName = "pwr",          icon = icon("dashboard")),
        menuItem("samplesize",   tabName = "samplesize",   icon = icon("dashboard")),
        menuItem("TrialSize",    tabName = "TrialSize",    icon = icon("dashboard")),
        menuItem("clusterPower", tabName = "clusterPower", icon = icon("dashboard")),
        menuItem("longpower",    tabName = "longpower",    icon = icon("dashboard")),
        menuItem("PowerTOST",    tabName = "PowerTOST",    icon = icon("dashboard")),
        sliderInput(inputId = "power",
                    label   = "Power (1 - Beta)",
                    value   = 0.9,
                    min     = 0,
                    max     = 1,
                    step    = 0.01,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "sig.level",
                    label   = "Significance Level",
                    value   = 0.01,
                    min     = 0.00001,
                    max     = 0.1,
                    step    = 0.00001,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "prop1",
                    label   = "Proportion 1",
                    value   = 0.9,
                    min     = 0,
                    max     = 1,
                    step    = 0.01,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "prop2",
                    label   = "Proportion 2",
                    value   = 0.8,
                    min     = 0,
                    max     = 1,
                    step    = 0.01,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "mean1",
                    label   = "Mean 1",
                    value   = 1,
                    min     = 0,
                    max     = 100,
                    step    = 0.1,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "sd1",
                    label   = "SD 1",
                    value   = 1,
                    min     = 0,
                    max     = 100,
                    step    = 0.1,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "mean2",
                    label   = "Mean 2",
                    value   = 1,
                    min     = 0,
                    max     = 100,
                    step    = 0.1,
                    round   = FALSE,
                    ticks   = TRUE),
        sliderInput(inputId = "sd2",
                    label   = "SD 2",
                    value   = 1,
                    min     = 0,
                    max     = 100,
                    step    = 0.1,
                    round   = FALSE,
                    ticks   = TRUE)
